name: Snyk PR Scan

on:
  push:
  workflow_dispatch:
  pull_request:
    branches:
      - '**'

jobs:
  snyk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Set up Maven
        run: mvn -version

      - name: Install Snyk
        run: npm install -g snyk

      - name: Auth Snyk
        run: snyk auth ${{ secrets.SNYK_TOKEN }}

      - name: Run Snyk scan
        run: snyk test --file=pom.xml 
